# Generated by Django 6.1.1 on 2026-09-09 13:20

import django.db.models.deletion
import scanning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_role"),
        ("bookings", "0002_ticket"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=scanning.models.new_scan_event_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("gate", models.CharField(max_length=50)),
                ("accepted", models.BooleanField()),
                ("reason", models.CharField(blank=True, max_length=30, null=True)),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "passenger_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("trip_title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="catalog.occurrence",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="accounts.user",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="bookings.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
