# Generated by Django 6.1.1 on 2026-09-10 05:51

import carts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_preferences'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(default=carts.models.new_cart_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.CharField(default=carts.models.new_hold_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('seat_labels', models.JSONField(blank=True, default=list)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='catalog.occurrence')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds', to='accounts.user')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='catalog.inventoryzone')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.CharField(default=carts.models.new_cart_item_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('leg_index', models.PositiveSmallIntegerField(default=0)),
                ('seat_labels', models.JSONField(blank=True, default=list)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('unit_price_minor', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.occurrence')),
                ('hold', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='carts.hold')),
            ],
        ),
    ]
