# Generated by Django 6.1.1 on 2026-09-08 01:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=accounts.models.new_user_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone_e164",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("locale", models.CharField(default="en-NP", max_length=10)),
                ("role", models.CharField(default="traveller", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
