# Generated by Django 6.1.1 on 2026-09-08 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("mode", models.CharField(max_length=10)),
                ("departs_at", models.DateTimeField()),
                ("arrives_at", models.DateTimeField(blank=True, null=True)),
                ("gates_open_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("base_price_minor", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("seats_sold", models.IntegerField(default=0)),
                (
                    "provider_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("kind", models.CharField(max_length=20)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(max_length=255)),
                ("name_ne", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=5)),
                ("timezone", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("modes", models.JSONField(default=list)),
                ("adapter_key", models.CharField(max_length=50)),
                ("is_self_serve", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryZone",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=100)),
                ("price_minor", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("is_reserved_seating", models.BooleanField(default=False)),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="catalog.occurrence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("mode", models.CharField(max_length=10)),
                ("code", models.CharField(blank=True, max_length=30, null=True)),
                ("title", models.CharField(max_length=255)),
                ("attributes", models.JSONField(default=dict)),
                (
                    "dest_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.place",
                    ),
                ),
                (
                    "origin_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.place",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="catalog.provider",
                    ),
                ),
                (
                    "venue_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.place",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="occurrence",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="catalog.service",
            ),
        ),
    ]
