# Generated by Django 6.1.1 on 2026-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fill_place_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('geometry', models.JSONField()),
                ('distance_km', models.FloatField()),
                ('duration_min', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
