# Generated by Django 6.1.1 on 2026-09-08 02:01

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_role"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=bookings.models.new_booking_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=bookings.models.new_reference,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("offer_id", models.CharField(max_length=64)),
                ("mode", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("provider_name", models.CharField(max_length=255)),
                ("departs_at", models.DateTimeField(blank=True, null=True)),
                ("contact_phone", models.CharField(max_length=20)),
                (
                    "contact_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_method", models.CharField(max_length=20)),
                ("passenger_count", models.PositiveSmallIntegerField(default=1)),
                ("subtotal_minor", models.IntegerField()),
                ("fees_minor", models.IntegerField()),
                ("total_minor", models.IntegerField()),
                ("currency", models.CharField(default="NPR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("created_via", models.CharField(default="web", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="catalog.occurrence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("is_lead", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
