# Generated by Django 6.1.1 on 2026-09-08 02:24

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=bookings.models.new_ticket_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=bookings.models.new_ticket_code,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("seat_label", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("redeemed", "Redeemed"),
                            ("void", "Void"),
                        ],
                        default="issued",
                        max_length=10,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "redeemed_gate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="bookings.booking",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="catalog.occurrence",
                    ),
                ),
                (
                    "passenger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="bookings.passenger",
                    ),
                ),
            ],
        ),
    ]
