# Generated by Django 6.1.1 on 2026-10-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_paid_at_booking_payment_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_label',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_label',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
